name: Build

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      # choose your default branch
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@v4.2.2
        with:
          ref: "builds"
          path: "builds"

      - name: Clean old builds
        run: rm $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Setup JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          distribution: "adopt"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Access Secrets
        env:
          CONSUMET_API: ${{ secrets.CONSUMET_API }}
          BYPASS_API: ${{ secrets.BYPASS_API }}
          SIMKL_API: ${{ secrets.SIMKL_API }}
          MOVIEBOX_SECRET_KEY_DEFAULT: ${{ secrets.MOVIEBOX_SECRET_KEY_DEFAULT }}
          MOVIEBOX_SECRET_KEY_ALT: ${{ secrets.MOVIEBOX_SECRET_KEY_ALT }}
          CASTLE_SUFFIX: ${{ secrets.CASTLE_SUFFIX }}
          CRICIFY_PROVIDER_SECRET1: ${{ secrets.CRICIFY_PROVIDER_SECRET1 }}
          CRICIFY_PROVIDER_SECRET2: ${{ secrets.CRICIFY_PROVIDER_SECRET2 }}
          PIKASHOW_API_KEY: ${{ secrets.PIKASHOW_API_KEY }}
          PIKASHOW_HMAC_SECRET: ${{ secrets.PIKASHOW_HMAC_SECRET }}
          CRICFY_FIREBASE_API_KEY: ${{ secrets.CRICFY_FIREBASE_API_KEY }}
          CRICFY_FIREBASE_APP_ID: ${{ secrets.CRICFY_FIREBASE_APP_ID }}
          CRICFY_FIREBASE_PROJECT_NUMBER: ${{ secrets.CRICFY_FIREBASE_PROJECT_NUMBER }}
          SKLIVE_KEY: ${{ secrets.SKLIVE_KEY }}
          SKLIVE_IV: ${{ secrets.SKLIVE_IV }}
          SKTECH_FIREBASE_APP_ID: ${{ secrets.SKTECH_FIREBASE_APP_ID }}
          SKTECH_FIREBASE_API_KEY: ${{ secrets.SKTECH_FIREBASE_API_KEY }}
          SKTECH_FIREBASE_PROJECT_NUMBER: ${{ secrets.SKTECH_FIREBASE_PROJECT_NUMBER }}
          CINETV_SECRET_KEY_ENCRYPTED: ${{ secrets.CINETV_SECRET_KEY_ENCRYPTED }}
          CINETV_DES_KEY: ${{ secrets.CINETV_DES_KEY }}
          CINETV_DES_IV: ${{ secrets.CINETV_DES_IV }}
          CINETV_AES_KEY: ${{ secrets.CINETV_AES_KEY }}
          CINETV_AES_IV: ${{ secrets.CINETV_AES_IV }}
          CINETV_WS_SECRET: ${{ secrets.CINETV_WS_SECRET }}
        run: |
          cd $GITHUB_WORKSPACE/src
          echo CONSUMET_API=$CONSUMET_API >> local.properties
          echo BYPASS_API=$BYPASS_API >> local.properties
          echo SIMKL_API=$SIMKL_API >> local.properties
          echo PIKASHOW_API_KEY=$PIKASHOW_API_KEY >> local.properties
          echo PIKASHOW_HMAC_SECRET=$PIKASHOW_HMAC_SECRET >> local.properties
          echo CRICFY_FIREBASE_API_KEY=$CRICFY_FIREBASE_API_KEY >> local.properties
          echo CRICFY_FIREBASE_APP_ID=$CRICFY_FIREBASE_APP_ID >> local.properties
          echo CRICFY_FIREBASE_PROJECT_NUMBER=$CRICFY_FIREBASE_PROJECT_NUMBER >> local.properties
          echo SKTECH_FIREBASE_APP_ID=$SKTECH_FIREBASE_APP_ID >> local.properties
          echo SKTECH_FIREBASE_API_KEY=$SKTECH_FIREBASE_API_KEY >> local.properties
          echo SKTECH_FIREBASE_PROJECT_NUMBER=$SKTECH_FIREBASE_PROJECT_NUMBER >> local.properties
          echo CINETV_SECRET_KEY_ENCRYPTED=$CINETV_SECRET_KEY_ENCRYPTED >> local.properties
          echo CINETV_DES_KEY=$CINETV_DES_KEY >> local.properties
          echo CINETV_DES_IV=$CINETV_DES_IV >> local.properties
          echo CINETV_AES_KEY=$CINETV_AES_KEY >> local.properties
          echo CINETV_AES_IV=$CINETV_AES_IV >> local.properties
          echo CINETV_WS_SECRET=$CINETV_WS_SECRET >> local.properties
    
      - name: Build Plugins
        env:
          MOVIEBOX_SECRET_KEY_DEFAULT: ${{ secrets.MOVIEBOX_SECRET_KEY_DEFAULT }}
          MOVIEBOX_SECRET_KEY_ALT: ${{ secrets.MOVIEBOX_SECRET_KEY_ALT }}
          CASTLE_SUFFIX: ${{ secrets.CASTLE_SUFFIX }}
          CRICIFY_PROVIDER_SECRET1: ${{ secrets.CRICIFY_PROVIDER_SECRET1 }}
          CRICIFY_PROVIDER_SECRET2: ${{ secrets.CRICIFY_PROVIDER_SECRET2 }}
          PIKASHOW_API_KEY: ${{ secrets.PIKASHOW_API_KEY }}
          PIKASHOW_HMAC_SECRET: ${{ secrets.PIKASHOW_HMAC_SECRET }}
          CRICFY_FIREBASE_API_KEY: ${{ secrets.CRICFY_FIREBASE_API_KEY }}
          CRICFY_FIREBASE_APP_ID: ${{ secrets.CRICFY_FIREBASE_APP_ID }}
          CRICFY_FIREBASE_PROJECT_NUMBER: ${{ secrets.CRICFY_FIREBASE_PROJECT_NUMBER }}
          SKLIVE_KEY: ${{ secrets.SKLIVE_KEY }}
          SKLIVE_IV: ${{ secrets.SKLIVE_IV }}
          SKTECH_FIREBASE_APP_ID: ${{ secrets.SKTECH_FIREBASE_APP_ID }}
          SKTECH_FIREBASE_API_KEY: ${{ secrets.SKTECH_FIREBASE_API_KEY }}
          SKTECH_FIREBASE_PROJECT_NUMBER: ${{ secrets.SKTECH_FIREBASE_PROJECT_NUMBER }}
          CINETV_SECRET_KEY_ENCRYPTED: ${{ secrets.CINETV_SECRET_KEY_ENCRYPTED }}
          CINETV_DES_KEY: ${{ secrets.CINETV_DES_KEY }}
          CINETV_DES_IV: ${{ secrets.CINETV_DES_IV }}
          CINETV_AES_KEY: ${{ secrets.CINETV_AES_KEY }}
          CINETV_AES_IV: ${{ secrets.CINETV_AES_IV }}
          CINETV_WS_SECRET: ${{ secrets.CINETV_WS_SECRET }}
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0   # do not error if nothing to commit
          git push --force